### ISSUE TITLE
 Won't run.

### ISSUE THREAD

**Issue by euiruhieer** [Hazza3100/Roblox-Cookie-Creator#2]
Inputted my captcha key, proxies, hit save with Python in PATH and everything, and it won't run.

**Comment by Hazza3100** [comment]
Open with cmd and show error

**Comment by euiruhieer** [comment]
> Open with cmd and show error

![image](https://user-images.githubusercontent.com/99937565/202909400-d3e5611d-87ad-4a83-abec-9628d013cc8f.png)

**Comment by Hazza3100** [comment]
Make the file.
