### ISSUE TITLE
alright my man

### ISSUE THREAD

**Issue by Tinxxz** [Hazza3100/Roblox-Cookie-Creator#5]
it reached 50 starts now u gotta add those juicy features

**Comment by Hazza3100** [comment]
I will integrate the features once I have some spare time.

**Comment by Imagine-YT** [comment]
I checked the roblox API, now the captcha stuff goes in the headers
![image](https://user-images.githubusercontent.com/74649094/235557092-a36eac14-be97-4683-9c1f-703da99ff6b5.png)

**Comment by Xyno12** [comment]
How do i get it to work? I install the zip file and there is a python main and some more files what now?

**Comment by Hazza3100** [comment]
Patched due to update.
