### ISSUE TITLE
i cant make accounts 

### ISSUE THREAD

**Issue by byfzfy** [Hazza3100/Roblox-Cookie-Creator#6]
"captchaio" is not defined
list index out of range
list index out of range
'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
list index out of range
list index out of range
list index out of range
'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
'NoneType' object is not subscriptable

**Comment by Hazza3100** [comment]
This is now achieved.
